### ISSUE TITLE
[REQUEST] Documentation on format?

### ISSUE THREAD

**Issue by ParzivalWolfram** [feuerpanda/DDexter#1]
I'd like some documentation on the format for Dex entries, especially for pictures.

**Comment by feuerpanda** [comment]
The project is abandoned, it just stands here for archival purposes.

**Comment by ParzivalWolfram** [comment]
that's not really a good answer, as this is undocumented for the program
and therefore means archival is incomplete, does it not?

**Comment by feuerpanda** [comment]
Thing is, I dont remember, and i abandoned for 2016.

 By a quick look into the messy display code, I can guess the dex pictures are of the png format, more i cant answer. 

I will mark the repo as archived, as i wont pick up the project again, on one hand because of copyright concerns, on the other hand has LPP-3DS isnt supported by its creator anymore and doesnt work on current homebrew launcher anymore. And that i dont even have a 3ds to debug this anymore.
